### get all customers
GET http://localhost:8080/api/customers

### create a new customer
POST http://localhost:8080/api/customers
Content-Type: application/json

{
    "first_name": "Erik",
    "middle_name": "Ko",
    "last_name": "Kokomo",
    "phone": "12347567",
    "email": "foo@bar.com",
    "notes": "tubular",
    "address_id": 10
}

### get by id
GET http://localhost:8080/api/customers/55

###
GET http://localhost:8080/api/customers?count=5&page=2

### get with pagination and search - count and page number
GET http://localhost:8080/api/customers?count=4&page=2&email=Krystina21@hotmail.com

### get with pagination - count and order by
GET http://localhost:8080/api/customers?count=200&order=updatedAt

### get with pagination and search - count and order by
GET http://localhost:8080/api/customers?count=200&order=updatedAt&email=Krystina21@hotmail.com


### GET customer by ID
GET http://localhost:8080/api/customers/102



### search by email
GET http://localhost:8080/api/customers?email=Krystina21@hotmail.com


### delete by id
DELETE http://localhost:8080/api/customers/2

### get with pagination
GET http://localhost:8080/api/customers?count=5

