### GET orders

GET http://localhost:8080/api/order


### GET orders by ID

GET http://localhost:8080/api/orders/5

### Delete order by ID

DELETE http://localhost:8080/api/orders/88
###

POST http://localhost:8080/api/orders
Content-Type: application/json

    {
      "customer_id": "2",
      "order_status": "0",
      "datetime_order_placed": "2021-07-28T13:46:10.991Z",
      "total_order_price": 935,
      "order_notes": "jkdjfkasjiejfkajskldf",
      "products": "1,4"
    
    }
