
###

GET http://localhost:8080/api/products

###Update product by ID
PUT http://localhost:8080/api/products/501?quantity=5
Content-Type: application/json




### GET product by Id
GET http://localhost:8080/api/products/1
